// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTwBZTnHhxsNLh8plt7yA5ehSdXgDkrrU',
    appId: '1:74585324107:web:871e391b3fc09320acebce',
    messagingSenderId: '74585324107',
    projectId: 'ecommerce-58a6e',
    authDomain: 'ecommerce-58a6e.firebaseapp.com',
    storageBucket: 'ecommerce-58a6e.appspot.com',
    measurementId: 'G-QZ59FGHPGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMDTZ-jqbynO-Rd4QEeS5QVbPd-Wc__q4',
    appId: '1:74585324107:android:4010221e763ddd5dacebce',
    messagingSenderId: '74585324107',
    projectId: 'ecommerce-58a6e',
    storageBucket: 'ecommerce-58a6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2OY5QVNlXywc99oytb5MJbFzVHCj5ItE',
    appId: '1:74585324107:ios:801074cd91a6228eacebce',
    messagingSenderId: '74585324107',
    projectId: 'ecommerce-58a6e',
    storageBucket: 'ecommerce-58a6e.appspot.com',
    androidClientId: '74585324107-bfppcgt0fkhvd9jvkr0jpaocpfifoql9.apps.googleusercontent.com',
    iosClientId: '74585324107-lf1603slavk12v10so0ok79jc8jhvamd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1Seller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2OY5QVNlXywc99oytb5MJbFzVHCj5ItE',
    appId: '1:74585324107:ios:801074cd91a6228eacebce',
    messagingSenderId: '74585324107',
    projectId: 'ecommerce-58a6e',
    storageBucket: 'ecommerce-58a6e.appspot.com',
    androidClientId: '74585324107-bfppcgt0fkhvd9jvkr0jpaocpfifoql9.apps.googleusercontent.com',
    iosClientId: '74585324107-lf1603slavk12v10so0ok79jc8jhvamd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1Seller',
  );
}
